### ISSUE TITLE
License

### ISSUE THREAD

**Issue by oleduc** [evuez/identicons#1]
Hi @evuez, I have forked your codebase and would like to use it in my projects, however, you have not chosen a license for your library, so I'm a bit afraid to use it.

It would be great if you could pick an open source license which allows commercial applications as well, such as the http://unlicense.org/ or the MIT license.

See other interesting licenses: http://choosealicense.com/

Thank you very much!

**Comment by evuez** [comment]
Sorry for the delay...

I just added a license file (MIT license), so don't be afraid to use it anymore :)
